# Change these first
owner: Pokemopsi # Your GitHub organization or username, where this repository lives
repo: upptime-upptime # The name of this repository

sites:
  - name: Sogo
    url: https://sogo.uni-osnabrueck.de
    method: POST
    maxResponseTime: 1000
  - name: Rechenzentrum Uni
    url: https://www.rz.uni-osnabrueck.de
    method: POST
    maxResponseTime: 1000
  - name: Stud.IP
    url: https://studip.uni-osnabrueck.de
  - name: Uni Bibliothek
    url: https://www.ub.uni-osnabrueck.de

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime-upptime/
  # https://pokemopsi.github.io/upptime-upptime/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Statuspage der Universität Osnabrück
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Help
      href: https://www.rz.uni-osnabrueck.de/dienste/beratung/beratungsteam/index.html
  theme: light

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
